name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: [8.1, 8.2, 8.3, 8.4]

    steps:
      - uses: actions/checkout@v4

      - name: 'Build Version Change'
        run: |
          export VERSION=${{ matrix.version }}
          envsubst '$VERSION' < Dockerfile.tpl | tee Dockerfile

      - name: Build image
        run: |
          export IMAGE_NAME=ci_php:${{ matrix.version }}
          docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Push image
        run: |
          export IMAGE_NAME=ci_php:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/luckyraul/php:${{ matrix.version }}-ci

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo $IMAGE_ID

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
      - name: Test Image PHP Version
        run: docker run --rm ci_php:${{ matrix.version }} php -v

      - name: Test Image composer Version
        run: docker run --rm ci_php:${{ matrix.version }} composer -V
  post_build:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Delete untagged ghcr LR
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ secrets.CR_PAT }}
          repository_owner: ${{ github.repository_owner }}
          owner_type: user
          package_name: php
      - name: Delete untagged ghcr Mygento
        uses: Chizkiyahu/delete-untagged-ghcr-action@v3
        with:
          token: ${{ secrets.CR_PAT }}
          repository_owner: mygento
          owner_type: org
          package_name: php
